### ISSUE TITLE
question about number of labels/joints

### ISSUE THREAD

**Issue by balakg** [shihenw/convolutional-pose-machines-release#19]
Hi Shihen,

I have a question about how the labels are formed from the MPII annotations. MPII provides 16 annotations, and the output of cpm seems to be 14 plus bkg. What is bkg? Also, I can't seem to determine at which point in the lmdb/prototxt generation sequence that you remove the two extra joints and add a bkg label. genJSON keeps all 16 joints, and it appears that genLMDB does as well. Thanks for the help!

**Comment by shihenw** [comment]
1) We kept everything raw in the LMDB. The removal of the 2 points of MPI happens in our transformer of caffe.
2) Bkg means background. It is a heatmap simply generated by 1 - max(sum of parts' heatmaps).

**Comment by balakg** [comment]
Thanks!
