### ISSUE TITLE
Missing trained Models to run CPM_demo.m

### ISSUE THREAD

**Issue by jjd10** [shihenw/convolutional-pose-machines-release#25]
Hi!! I could not find your caffe.model to run the demo file. I get the following error message when I run CPM_demo.m

`../model/_trained_MPI/pose_iter_985000_addLEEDS.caffemodel does not exist`

and when I checked in the uploaded git, I could just locate .ptototxt file but no trained caffe models. Could you please share the models.

Thanks!

**Comment by shihenw** [comment]
You have to run `testing/get_model.sh` to retreive trained models from our web server.

**Comment by jjd10** [comment]
Thanks! Sorry i missed it from readme.
