### ISSUE TITLE
occlusions and out of bounds

### ISSUE THREAD

**Issue by balakg** [shihenw/convolutional-pose-machines-release#29]
Hi,

How do you handle joints that are occluded or out of image bounds during training? I see in datatransformer that isVisible = 0 for occluded, and 2 for out of bounds. Do you still train on those annotations, or do you discard them? Thanks!

**Comment by shihenw** [comment]
For occluded (isVisible=0) I still put Gaussian peaks on the label. For truncated ones I don't put peaks.
