### ISSUE TITLE
concatenation order

### ISSUE THREAD

**Issue by gulvarol** [shihenw/convolutional-pose-machines-release#31]
Hi,

I am not familiar with caffe, and i converted your models to Torch. But I have a question concerning the concatenation layer to make sure i am not introducing wrong conversion. The number of channels after each concatenation is 48. Is the order of the channels [32, 15, 1] like the following?

For example, the input to `concat_stage3`:
1) 32 from `relu1_stage3`
2) 15 from `Mconv5_stage2`
3) 1 from `pool_center_lower`

Thanks!

**Comment by shihenw** [comment]
The order should exactly follow the order they are written in prototxt.

**Comment by gulvarol** [comment]
Thanks!
