### ISSUE TITLE
Problem accessing pearl.vasc.ri.cmu.edu Is it temporary?

### ISSUE THREAD

**Issue by agarwal-shubham** [shihenw/convolutional-pose-machines-release#35]
I ran the script to download models but I was refused connection to the site to download the caffe models. I thought it was a college proxy issue, but trying without proxy gives the same error. Is this a temporary problem because of maybe server maintenance, if not where if possible can I get access to the trained models?

**Comment by shihenw** [comment]
Should be fixed. Our server was being upgrading.
