### ISSUE TITLE
Is there any demo to test multi human pose?

### ISSUE THREAD

**Issue by mindcont** [shihenw/convolutional-pose-machines-release#37]
Hi, @shihenw 
I have seen your video on youtube,it`s impressive,especially this [video](https://www.youtube.com/watch?v=lc30OP4tfHE&list=PLNh5A7HtLRcpsMfvyG0DED-Dr4zW5Lpcg&index=8).

[![IMAGE ALT TEXT HERE](https://cloud.githubusercontent.com/assets/13744152/21286940/37706522-c49c-11e6-9038-ecf92bab2436.jpg)](http://www.youtube.com/watch?v=lc30OP4tfHE&list=PLNh5A7HtLRcpsMfvyG0DED-Dr4zW5Lpcg&index=8)

Is there any possible ways which i can do to test a multi human image with your center-deploy file?

Much thanks as much as i can!

**Comment by shihenw** [comment]
This file is explaining the pipeline: https://github.com/shihenw/convolutional-pose-machines-release/blob/master/testing/python/demo.ipynb. But for realtime performance you need to speedup components other than CNN evaluation.

**Comment by mindcont** [comment]
thanks ,that helped me a lot. 😸
