### ISSUE TITLE
kernel size: 9 vs multiple 3s

### ISSUE THREAD

**Issue by hyqneuron** [shihenw/convolutional-pose-machines-release#39]
Hi Shih-En,

Thanks for the great work. I've noticed genProto.py generates models with 9x9 kernels whereas the prototxts under model directory contain multiple 3x3 kernels instead. Is it because multiple 3x3 kernels are faster? What are the differences? Thanks!

Yunqing

**Comment by shihenw** [comment]
Yunqing,

The model with 9x9 kernels were the older version when we trained from scratch. Later on we found training with pre-trained parameters in VGG network in stage 1 of the CPM is beneficial. That's why you see multiple 3x3 there: it's part of VGG net.

**Comment by hyqneuron** [comment]
That makes sense. Thanks!
