### ISSUE TITLE
About the version

### ISSUE THREAD

**Issue by tangyudi** [shihenw/convolutional-pose-machines-release#4]
Thank you for sharing your code.I am not familiar with matlab,do you have a python version?And to run the code is it necessary to download your caffe?I have already installed the official caffe.

**Comment by shihenw** [comment]
Python testing code will be the very next push. I'll try harder to find a chance to do it sooner.

If you're only trying testing part, official caffe might work, but like what was reported, caffe newer than some particular version is not compatible right now unfortunately. For training, you will need our caffe.

**Comment by frankmanbb** [comment]
I wonder if the python version is available now? Thank you

**Comment by shihenw** [comment]
We do have a ipython notebook demo code right now. Please check `testing/python/demo.ipynb`.
