### ISSUE TITLE
Runtime Performance

### ISSUE THREAD

**Issue by kartikeyashivigoyal** [shihenw/convolutional-pose-machines-release#44]
Hello! 

I am thinking of training the model on Intel Xeon processor. Have you tried running caffe on Xeon for either training or scoring?

Also, which Nvidia card are you using and what are your training and scoring times? I am considering if I should invest in a expensive graphics card or not :)

Thanks,
HPCNerd

**Comment by shihenw** [comment]
I haven't tried Xeon with caffe...you probably need a great implementation of convolutions for that. Along the road I've been training with Titan X (maxwell), GTX 1080, and Titan X (pascal). Either one of these should be fine.
