### ISSUE TITLE
What does the target_dist mean?

### ISSUE THREAD

**Issue by WolffyChen** [shihenw/convolutional-pose-machines-release#46]
Hello Wei,

Thank you for this great work. I am confused about what the target_dist is? I only know that it is related to the scale of the picture. 
And I also see that you set it to 41/35, why this value? If I want to train it uses another data set, what value should I set it to fit my data set?

Thank you very much!
Hope Reply.

**Comment by shihenw** [comment]
Hi, 

It is used to control scaling factor of training samples. With a pre-defined input size 368 * 368, we need to make sure each training sample is roughly scaled such that the interested person is nicely fit in 368 * 368 box. 41/35, or 1.171 (sorry the division doesn't mean anything), is a result of empirical tuning that only a acceptably small fraction of joints will be truncated. If you train on other dataset (with proper per-sample scaling labels), just adjust this "target_dist" in the same way.

**Comment by WolffyChen** [comment]
Thank you for your reply. According to your answer, while reading the source code, I have understand it.
