### ISSUE TITLE
 has no field named "cpm_transform_param"

### ISSUE THREAD

**Issue by NIEYALI** [shihenw/convolutional-pose-machines-release#47]
Dear shihenw,
thanks for your great work. but I found the problem following:
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 11:23: Message type "caffe.LayerParameter" has no field named "cpm_transform_param".
F0315 10:48:45.572080  3290 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: pose_train_test.prototxt
*** Check failure stack trace: ***
Do you know the reason?
thank you

**Comment by shihenw** [comment]
This problem is probably caused by that you're not linking to our version of caffe. I know this is a bit annoying building another copy of caffe, and we're planning to get rid of that, but for now please do so. It is a sub-directory in the repo.

**Comment by NIEYALI** [comment]
Thanks shihen, I will try again
