### ISSUE TITLE
Meaning of P + 1 part for background

### ISSUE THREAD

**Issue by sieu-n** [shihenw/convolutional-pose-machines-release#79]
I was reading the paper "Convolutional Pose Machines" and couldn't understand why the model outputted P+1 channels including the channel for the background. What do you intend by predicting the background, and how is the background prediction evaluated?

Sorry if this is an obvious question.

**Comment by vanheukelomdean** [comment]
I am also confused by this... how is the loss measured for this belief map

**Comment by alecda573** [comment]
The background is the P+1 belief map. It is calculated by generating a map as the max across the previous heatmaps and then swapping black for white pixels
