### ISSUE TITLE
Batch size recommendation

### ISSUE THREAD

**Issue by shenxiaolu1984** [shihenw/convolutional-pose-machines-release#8]
Thank you for sharing your code!

How long does it take you to train the model?

I'm using a 12 GB NVIDIA TitanX GPU, could you recommend a proper batch size?

**Comment by shihenw** [comment]
Batch size 8 should fit into 12 GB memory. My trained model was trained with 16, enabled by data parallelism with multiple GPUs. But 8 would produce comparable results.

**Comment by shenxiaolu1984** [comment]
Thanks!
